### ISSUE TITLE
Where do I download the contents of the MeshApp/tor folder from?

### ISSUE THREAD

**Issue by mwherman2000** [TechnitiumSoftware/Mesh#9]
![image](https://user-images.githubusercontent.com/6101736/202999661-726ab2df-46c6-4f42-9d21-8630afa19f65.png)

**Comment by mwherman2000** [comment]
It looks like these files can be found in the Tor Windows Expert Bundle can be downloaded from here: https://www.torproject.org/download/tor/

Correct?

**Comment by ShreyasZare** [comment]
Yes, you can download the "Windows Expert Bundle" and unzip the files in the project folder.

**Comment by mwherman2000** [comment]
I also had to make a copy of the tor folder under the Debug folder (after I downloaded and copied the files to the tor folder in the VS project) and everything worked grand. 🙂
